# -*- coding: utf-8 -*-

"""
scrapingbee

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Instruction1(object):

    """Implementation of the 'Instruction1' model.

    TODO: type model description here.

    Attributes:
        wait_for_and_click (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "wait_for_and_click": 'wait_for_and_click'
    }

    def __init__(self,
                 wait_for_and_click=None):
        """Constructor for the Instruction1 class"""

        # Initialize members of the class
        self.wait_for_and_click = wait_for_and_click 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        wait_for_and_click = dictionary.get("wait_for_and_click") if dictionary.get("wait_for_and_click") else None
        # Return an object of this model
        return cls(wait_for_and_click)
