# -*- coding: utf-8 -*-

"""
scrapingbee

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Instruction3(object):

    """Implementation of the 'Instruction3' model.

    TODO: type model description here.

    Attributes:
        scroll_y (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "scroll_y": 'scroll_y'
    }

    def __init__(self,
                 scroll_y=None):
        """Constructor for the Instruction3 class"""

        # Initialize members of the class
        self.scroll_y = scroll_y 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        scroll_y = dictionary.get("scroll_y") if dictionary.get("scroll_y") else None
        # Return an object of this model
        return cls(scroll_y)
