# -*- coding: utf-8 -*-

"""
scrapingbee

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Instruction4(object):

    """Implementation of the 'Instruction4' model.

    TODO: type model description here.

    Attributes:
        fill (List[str]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "fill": 'fill'
    }

    def __init__(self,
                 fill=None):
        """Constructor for the Instruction4 class"""

        # Initialize members of the class
        self.fill = fill 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        fill = dictionary.get("fill") if dictionary.get("fill") else None
        # Return an object of this model
        return cls(fill)
