# -*- coding: utf-8 -*-

"""
scrapingbee

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Search(object):

    """Implementation of the 'search' model.

    TODO: type model description here.

    Attributes:
        name (str): TODO: type description here.
        link (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": 'name',
        "link": 'link'
    }

    def __init__(self,
                 name=None,
                 link=None):
        """Constructor for the Search class"""

        # Initialize members of the class
        self.name = name 
        self.link = link 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get("name") if dictionary.get("name") else None
        link = dictionary.get("link") if dictionary.get("link") else None
        # Return an object of this model
        return cls(name,
                   link)
