# -*- coding: utf-8 -*-

"""
scrapingbee

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TopStories(object):

    """Implementation of the 'top_stories' model.

    TODO: type model description here.

    Attributes:
        title (str): TODO: type description here.
        link (str): TODO: type description here.
        source (str): TODO: type description here.
        data (str): TODO: type description here.
        position (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "title": 'title',
        "link": 'link',
        "source": 'source',
        "data": 'data',
        "position": 'position'
    }

    def __init__(self,
                 title=None,
                 link=None,
                 source=None,
                 data=None,
                 position=None):
        """Constructor for the TopStories class"""

        # Initialize members of the class
        self.title = title 
        self.link = link 
        self.source = source 
        self.data = data 
        self.position = position 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        title = dictionary.get("title") if dictionary.get("title") else None
        link = dictionary.get("link") if dictionary.get("link") else None
        source = dictionary.get("source") if dictionary.get("source") else None
        data = dictionary.get("data") if dictionary.get("data") else None
        position = dictionary.get("position") if dictionary.get("position") else None
        # Return an object of this model
        return cls(title,
                   link,
                   source,
                   data,
                   position)
