# -*- coding: utf-8 -*-

"""
scrapingbee

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from scrapingbee.api_helper import APIHelper


class GoogleSearchAPIControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(GoogleSearchAPIControllerTests, cls).setUpClass()
        cls.controller = cls.client.google_search_api
        cls.response_catcher = cls.controller.http_call_back

