# -*- coding: utf-8 -*-

"""
scrapingbee

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from apimatic_core.utilities.file_helper import FileHelper
from scrapingbee.api_helper import APIHelper


class HTMLAPIControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(HTMLAPIControllerTests, cls).setUpClass()
        cls.controller = cls.client.html_api
        cls.response_catcher = cls.controller.http_call_back

    # Todo: Add description for test test_usage_information
    def test_usage_information(self):

        # Perform the API call through the SDK function
        self.controller.usage_information()

        # Test response code
        assert self.response_catcher.response.status_code == 200

